---
- name: Create app directory
  ansible.builtin.file:
    path: /opt/bodima
    state: directory
    mode: '0755'

- name: Copy compose file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../compose.prod.yml"
    dest: /opt/bodima/compose.yml


- name: Create env file
  ansible.builtin.copy:
    dest: /opt/bodima/.env
    content: |
      BACKEND_IMAGE={{ backend_image }}
      FRONTEND_IMAGE={{ frontend_image }}
      SPRING_DATASOURCE_URL={{ spring_datasource_url }}
      SPRING_DATASOURCE_USERNAME={{ spring_datasource_username }}
      SPRING_DATASOURCE_PASSWORD={{ spring_datasource_password }}
      AWS_REGION={{ aws_region }}

- name: Login to ECR
  ansible.builtin.shell: |
    aws ecr get-login-password --region {{ aws_region }} | \
    docker login --username AWS --password-stdin {{ backend_image.split('/')[0] }}
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
  args:
    executable: /bin/bash

- name: Pull images
  ansible.builtin.shell: |
    docker pull {{ backend_image }}
    docker pull {{ frontend_image }}
  args:
    executable: /bin/bash

- name: Deploy stack
  ansible.builtin.shell: |
    cd /opt/bodima
    /usr/local/bin/docker-compose --env-file .env -f compose.yml up -d
  args:
    executable: /bin/bash
