[web]
# Replace with your EC2 public DNS or IP
web1 ansible_host=15.206.100.88 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/bodima.pem

[all:vars]
backend_image=612931695482.dkr.ecr.ap-south-1.amazonaws.com/bodima-backend:latest
frontend_image=612931695482.dkr.ecr.ap-south-1.amazonaws.com/bodima-frontend:latest
# Using RDS (set these after terraform apply outputs)
spring_datasource_url=jdbc:mysql://bodima-db.c1wa8008eb0x.ap-south-1.rds.amazonaws.com:3306/bodima
spring_datasource_username=admin
spring_datasource_password=Admin200142
aws_region=ap-south-1
